[build]
  # Direktori tempat file frontend Anda berada
  publish = "public"
  # Direktori tempat file backend Python Anda berada
  functions = "api"

[[redirects]]
  # Arahkan semua request ke /api/* ke fungsi backend kita
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200